# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-07-06T20:03:51Z"
  labels:
    app: nginx-pod
  name: nginx-pod
spec:
  containers:
  - args:
    - nginx
    - -g
    - daemon off;
    image: docker.io/library/nginx:1.23.3-alpine
    name: nginx
    ports:
    - containerPort: 80
      hostPort: 8080
    tty: true

